// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnRj7fVbcIFfqXsnN-hQShBxAdrm-IcNM',
    appId: '1:465545379499:android:058641c4c43cd3e4fb01ee',
    messagingSenderId: '465545379499',
    projectId: 'project-poke-f7a8c',
    storageBucket: 'project-poke-f7a8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfgrd4ETtzodxP9R3hygDo78hKqknc1Mw',
    appId: '1:465545379499:ios:a88c9fba6b064ba3fb01ee',
    messagingSenderId: '465545379499',
    projectId: 'project-poke-f7a8c',
    storageBucket: 'project-poke-f7a8c.appspot.com',
    androidClientId: '465545379499-o65lul42imin7k2pf1nk8ecmh1gnkeql.apps.googleusercontent.com',
    iosClientId: '465545379499-bgcl6vnct756fktkpb6vc103ois51hib.apps.googleusercontent.com',
    iosBundleId: 'com.lissete.pokemonprueba',
  );

}